version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=itemsdb
    depends_on:
      - mysql
    volumes:
      - ./src:/app
    command: python app.py

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=itemsdb
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
